# Generated by Django 5.2.10 on 2026-02-07 22:34

import examination_tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.IntegerField()),
                (
                    "task_screen",
                    models.FileField(
                        upload_to=examination_tasks.models.exam_task_upload_path,
                        verbose_name="Task PDF",
                    ),
                ),
                (
                    "task_content",
                    models.TextField(
                        blank=True,
                        help_text="The extracted content of the task from the PDF file.",
                    ),
                ),
                (
                    "task_pages",
                    models.CharField(
                        blank=True,
                        help_text="Page number(s) in the PDF, e.g., '5' or '5-6'.",
                        max_length=20,
                        verbose_name="Task Pages",
                    ),
                ),
                (
                    "answer_pages",
                    models.CharField(
                        blank=True,
                        help_text="Page number(s) in the PDF with the solution.",
                        max_length=20,
                        verbose_name="Answer Pages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Task",
                "verbose_name_plural": "Exam Tasks",
                "ordering": ["exam", "task_id"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.IntegerField(
                        choices=[(1, "Matriculation Exam"), (2, "Eighth Grade Exam")],
                        default=1,
                        verbose_name="Exam type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[(1, "Mathematics"), (2, "Physics")],
                        default=1,
                        max_length=10,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2002, "2002"),
                            (2003, "2003"),
                            (2004, "2004"),
                            (2005, "2005"),
                            (2006, "2006"),
                            (2007, "2007"),
                            (2008, "2008"),
                            (2009, "2009"),
                            (2010, "2010"),
                            (2011, "2011"),
                            (2012, "2012"),
                            (2013, "2013"),
                            (2014, "2014"),
                            (2015, "2015"),
                            (2016, "2016"),
                            (2017, "2017"),
                            (2018, "2018"),
                            (2019, "2019"),
                            (2020, "2020"),
                            (2021, "2021"),
                            (2022, "2022"),
                            (2023, "2023"),
                            (2024, "2024"),
                            (2025, "2025"),
                            (2026, "2026"),
                        ]
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("tasks_link", models.FileField(upload_to="exam_pdfs/")),
                (
                    "solutions_link",
                    models.FileField(
                        blank=True, null=True, upload_to="exam_answers_pdfs/"
                    ),
                ),
                (
                    "tasks_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of tasks in this exam"
                    ),
                ),
                (
                    "level_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Basic"), (2, "Extended")],
                        help_text="Exam level: basic or extended (Matriculation only)",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "-exam_type", "-level_type"],
                "unique_together": {("year", "month", "level_type", "exam_type")},
            },
        ),
    ]
