# Generated by Django 5.2.6 on 2025-10-20 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examination_tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examtask",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_exam_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examtask",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="examination_tasks.exam",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="examination_tasks.book",
                verbose_name="Book",
            ),
        ),
        migrations.AddField(
            model_name="examtask",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_tasks",
                to="examination_tasks.section",
                verbose_name="Section",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="examination_tasks.section",
                verbose_name="Section",
            ),
        ),
        migrations.AddField(
            model_name="examtask",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="examination_tasks.topic",
                verbose_name="Topic",
            ),
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_training_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_tasks",
                to="examination_tasks.section",
                verbose_name="Chapter (optional)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("section", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="examtask",
            unique_together={("exam", "task_id")},
        ),
    ]
