# Generated by Django 5.2.3 on 2025-06-26 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examination_tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mathmatriculationtrainingtasks",
            name="done_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_matriculation_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mathmatriculationtasks",
            unique_together={("exam", "task_id")},
        ),
    ]
