# Generated by Django 5.2.10 on 2026-02-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("examination_tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examtask",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_exam_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examtask",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="examination_tasks.exam",
            ),
        ),
        migrations.AddField(
            model_name="examtask",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_tasks",
                to="courses.section",
                verbose_name="Section",
            ),
        ),
        migrations.AddField(
            model_name="examtask",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="courses.topic",
                verbose_name="Topic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examtask",
            unique_together={("exam", "task_id")},
        ),
    ]
