# Generated by Django 5.2.3 on 2025-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mathmatriculationtasks",
            name="content",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="The extracted content of the task from the PDF file.",
            ),
        ),
    ]
