# Generated by Django 5.2.10 on 2026-03-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.IntegerField(
                choices=[(1, "Mathematics"), (2, "Physics")],
                default=1,
                verbose_name="Subject",
            ),
        ),
    ]
