# Generated by Django 5.2.6 on 2025-10-26 18:10

import examination_tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.CharField(
                choices=[(1, "Mathematics"), (2, "Physics")],
                default=1,
                max_length=10,
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="examtask",
            name="task_screen",
            field=models.FileField(
                upload_to=examination_tasks.models.exam_task_upload_path,
                verbose_name="Task PDF",
            ),
        ),
    ]
