# Generated by Django 5.2.3 on 2025-07-29 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0003_mathmatriculationtasks_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["-year", "-month", "-level_type"]},
        ),
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together={("year", "month", "level_type")},
        ),
        migrations.RemoveField(
            model_name="mathmatriculationtasks",
            name="type",
        ),
        migrations.AddField(
            model_name="mathmatriculationtasks",
            name="answer",
            field=models.CharField(
                blank=True,
                help_text="The correct answer or solution to the task.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mathmatriculationtasks",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_exam_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mathmatriculationtasks",
            name="pages",
            field=models.CharField(
                blank=True,
                help_text="Page number(s) in the PDF, e.g., '5' or '5-6'.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="solutions_link",
            field=models.FileField(upload_to="", verbose_name="Solutions link"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="tasks_link",
            field=models.FileField(upload_to="", verbose_name="Tasks link"),
        ),
        migrations.AlterField(
            model_name="mathmatriculationtrainingtasks",
            name="done_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_training_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
