# Generated by Django 5.2.3 on 2025-07-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "examination_tasks",
            "0004_alter_exam_options_alter_exam_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="solutions_link",
            field=models.FileField(
                blank=True, null=True, upload_to="exam_answers_pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="tasks_link",
            field=models.FileField(upload_to="exam_pdfs/"),
        ),
    ]
