# Generated by Django 5.2.3 on 2025-08-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0006_book_section_and_more"),
        ("training_calendar", "0003_alter_scheduledtask_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MathMatriculationTasks",
        ),
        migrations.DeleteModel(
            name="MathMatriculationTrainingTasks",
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("book", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="examtask",
            unique_together={("exam", "task_id")},
        ),
    ]
