# Generated by Django 5.2.3 on 2025-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0007_delete_mathmatriculationtasks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examtask",
            name="task_content",
            field=models.TextField(
                blank=True,
                help_text="The extracted content of the task from the PDF file.",
                verbose_name="Task Content",
            ),
        ),
    ]
