# Generated by Django 5.2.3 on 2025-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_type",
            field=models.IntegerField(
                choices=[(1, "Student"), (2, "Teacher"), (3, "Admin")], default=1
            ),
        ),
    ]
