# Generated by Django 5.2.10 on 2026-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Base"), (2, "Premium"), (3, "Trial"), (4, "Ultimate")],
                default=1,
            ),
        ),
    ]
