# Generated by Django 5.2.10 on 2026-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="currency",
            field=models.CharField(default="pln", max_length=3),
        ),
    ]
