# Generated by Django 5.2.10 on 2026-04-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_plan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userplan",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
