# Generated by Django 5.2.10 on 2026-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_plan_stripe_price_id_userplan_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplan",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
