# Generated by Django 5.2.10 on 2026-02-07 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "author",
                    models.CharField(blank=True, max_length=255, verbose_name="Author"),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Publication Year"
                    ),
                ),
                (
                    "school_level",
                    models.CharField(
                        choices=[(1, "Primary School"), (2, "Secondary School")],
                        max_length=20,
                        verbose_name="School Level",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[(1, "Mathematics"), (2, "Physics")],
                        default=1,
                        max_length=10,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (7, "7th Grade - Primary"),
                            (8, "8th Grade - Primary"),
                            (9, "1st Year - Secondary"),
                            (10, "2nd Year - Secondary"),
                            (11, "3rd Year - Secondary"),
                            (12, "4th Year - Secondary"),
                        ],
                        help_text="Leave empty for books covering multiple grades",
                        null=True,
                        verbose_name="Target Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["school_level", "grade", "subject", "title"],
            },
        ),
        migrations.CreateModel(
            name="TrainingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_content", models.TextField(verbose_name="Task Content")),
                ("answer", models.CharField(max_length=255, verbose_name="Answer")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tasks_images/",
                        verbose_name="Task Image (optional)",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Intermediate"), (3, "Advanced")],
                        default=2,
                        verbose_name="Difficulty Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Task",
                "verbose_name_plural": "Training Tasks",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Linear Equations', 'Thermodynamics', 'Kinematics'",
                        max_length=255,
                        verbose_name="Section Name",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.book",
                        verbose_name="Book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Specific topic",
                        max_length=255,
                        verbose_name="Topic name",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="courses.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["section", "name"],
            },
        ),
    ]
