# Generated by Django 5.2.10 on 2026-02-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingtask",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_training_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.section",
                verbose_name="Chapter (optional)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("section", "name")},
        ),
    ]
