# Generated by Django 5.2.10 on 2026-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="section",
            name="book",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.CharField(blank=True, max_length=500, verbose_name="Author"),
        ),
        migrations.AddField(
            model_name="section",
            name="books",
            field=models.ManyToManyField(
                related_name="sections", to="courses.book", verbose_name="Books"
            ),
        ),
    ]
