# Generated by Django 5.2.10 on 2026-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_remove_book_author_remove_section_book_book_authors_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="school_level",
            field=models.IntegerField(
                choices=[(1, "Primary School"), (2, "Secondary School")],
                max_length=20,
                verbose_name="School Level",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="subject",
            field=models.IntegerField(
                choices=[(1, "Mathematics"), (2, "Physics")],
                default=1,
                max_length=10,
                verbose_name="Subject",
            ),
        ),
    ]
