# Generated by Django 5.2.10 on 2026-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_book_school_level_alter_book_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_type",
            field=models.IntegerField(
                choices=[(1, "Textbook"), (2, "Task Collection"), (3, "Work Cards")],
                default=1,
                max_length=20,
                verbose_name="Book Type",
            ),
            preserve_default=False,
        ),
    ]
