# Generated by Django 5.2.10 on 2026-03-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_book_book_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={},
        ),
        migrations.RemoveField(
            model_name="section",
            name="books",
        ),
        migrations.AddField(
            model_name="section",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (7, "7th Grade - Primary"),
                    (8, "8th Grade - Primary"),
                    (9, "1st Year - Secondary"),
                    (10, "2nd Year - Secondary"),
                    (11, "3rd Year - Secondary"),
                    (12, "4th Year - Secondary"),
                ],
                default=9,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section",
            name="subject",
            field=models.IntegerField(
                choices=[(1, "Mathematics"), (2, "Physics")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="book_type",
            field=models.IntegerField(
                choices=[(1, "Textbook"), (2, "Task Collection"), (3, "Work Cards")],
                verbose_name="Book Type",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="school_level",
            field=models.IntegerField(
                choices=[(1, "Primary School"), (2, "Secondary School")],
                verbose_name="School Level",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="subject",
            field=models.IntegerField(
                choices=[(1, "Mathematics"), (2, "Physics")],
                default=1,
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
