# Generated by Django 5.2.10 on 2026-03-21 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_section_options_remove_section_books_and_more"),
        ("videos", "0003_alter_videotimestamp_timestamp_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingtask",
            name="completed_by",
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_tasks",
                to="courses.book",
                verbose_name="Book",
            ),
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="explanation_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_tasks",
                to="videos.video",
                verbose_name="Explanation Video",
            ),
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserTaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.trainingtask",
                        verbose_name="Task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Task Completion",
                "verbose_name_plural": "User Task Completions",
                "unique_together": {("user", "task")},
            },
        ),
    ]
