# Generated by Django 5.2.10 on 2026-03-21 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_remove_trainingtask_completed_by_trainingtask_book_and_more"),
        ("videos", "0003_alter_videotimestamp_timestamp_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingtask",
            name="explanation_video",
        ),
        migrations.AddField(
            model_name="trainingtask",
            name="explanation_timestamp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_tasks",
                to="videos.videotimestamp",
            ),
        ),
    ]
