# Generated by Django 5.2.10 on 2026-03-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_remove_trainingtask_explanation_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingtask",
            name="level",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Intermediate"), (3, "Advanced")],
                verbose_name="Difficulty Level",
            ),
        ),
    ]
