# Generated by Django 5.2.10 on 2026-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_trainingtask_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingtask",
            name="source",
            field=models.IntegerField(
                choices=[(1, "Book"), (2, "Worksheet/Generator")],
                default=1,
                verbose_name="Task Source",
            ),
            preserve_default=False,
        ),
    ]
