# Generated by Django 5.2.10 on 2026-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_trainingtask_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertaskcompletion",
            name="completed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
