# Generated by Django 5.2.10 on 2026-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_usertaskcompletion_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingtask",
            name="answer",
            field=models.TextField(
                help_text="Use $...$ for inline math, e.g., $x=2$",
                verbose_name="Answer",
            ),
        ),
        migrations.AlterField(
            model_name="trainingtask",
            name="task_content",
            field=models.TextField(
                help_text="Use $...$ for inline math, e.g., $x=2$",
                verbose_name="Task Content",
            ),
        ),
    ]
