# Generated by Django 5.2.6 on 2026-01-03 12:18

import django.db.models.deletion
import motifs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examination_tasks", "0004_alter_exam_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[(1, "Mathematics"), (2, "Physics")],
                        default=1,
                        max_length=10,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "level_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Basic"), (2, "Extended")],
                        help_text="Motif level: basic or extended (Matriculation only)",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="Whole motif content",
                        max_length=255,
                        verbose_name="Motif content",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Explanation about chosen motif",
                        verbose_name="answer",
                    ),
                ),
                (
                    "answer_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Motif explanation picture if needed",
                        null=True,
                        upload_to=motifs.models.motif_image_path,
                    ),
                ),
                (
                    "is_in_matriculation_sheets",
                    models.BooleanField(
                        default=False, verbose_name="If exists in matriculation sheets"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Whether students must learn this motif",
                        verbose_name="Mandatory for students",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motifs",
                        to="examination_tasks.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motif in subject",
                "verbose_name_plural": "Motifs in subject",
                "ordering": ["subject", "section", "level_type"],
            },
        ),
    ]
