# Generated by Django 5.2.6 on 2026-01-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motifs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="motif",
            options={
                "ordering": ["subject", "section", "level_type"],
                "verbose_name": "Motif",
                "verbose_name_plural": "Motifs",
            },
        ),
        migrations.AlterField(
            model_name="motif",
            name="level_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Basic"), (2, "Extended")],
                help_text="Motif level: basic or extended (Matriculation only)",
                null=True,
                verbose_name="Level",
            ),
        ),
    ]
