# Generated by Django 5.2.6 on 2026-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motifs", "0002_alter_motif_options_alter_motif_level_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motif",
            name="subject",
            field=models.IntegerField(
                choices=[(1, "Mathematics"), (2, "Physics")],
                default=1,
                max_length=10,
                verbose_name="Subject",
            ),
        ),
    ]
