# Generated by Django 5.2.3 on 2025-06-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("youtube_url", models.URLField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Real numbers"),
                            (2, "Language of mathematics"),
                            (3, "Systems of equations"),
                            (4, "Functions"),
                            (5, "Linear function"),
                            (6, "Planimetry"),
                            (7, "Quadratic function"),
                            (8, "Polynomials"),
                            (9, "Measurable function"),
                            (10, "Trigonometry"),
                            (11, "Planimetry circles"),
                            (12, "Exponential and logarithmic functions"),
                            (13, "Trigonometric functions"),
                            (14, "Analytical geometry"),
                            (15, "Sequences"),
                            (16, "Differential calculus"),
                            (17, "Statistics"),
                            (18, "Probability"),
                            (19, "Stereometry"),
                        ]
                    ),
                ),
                ("subcategory", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[("1", "Primary School"), ("2", "Secondary School")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("start_time", models.DurationField(help_text="Format: HH:MM:SS")),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Exercise"), ("2", "Task")], max_length=10
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timestamps",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
