# Generated by Django 5.2.10 on 2026-02-07 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("youtube_url", models.URLField()),
                (
                    "subject",
                    models.IntegerField(
                        choices=[(1, "Mathematics"), (2, "Physics")],
                        verbose_name="Subject",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "Primary School"), (2, "Secondary School")],
                        verbose_name="School Level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="courses.section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("start_time", models.DurationField(help_text="Format: HH:MM:SS")),
                (
                    "timestamp_type",
                    models.IntegerField(choices=[(1, "Exercise"), (2, "Task")]),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timestamps",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Timestamp",
                "verbose_name_plural": "Video Timestamps",
                "ordering": ["start_time"],
            },
        ),
    ]
