# Generated by Django 5.2.10 on 2026-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videotimestamp",
            name="timestamp_type",
            field=models.IntegerField(
                choices=[(1, "Exercise"), (2, "Task"), (3, "Lecture")]
            ),
        ),
    ]
