# Generated by Django 5.2.10 on 2026-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_videotimestamp_timestamp_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videotimestamp",
            name="timestamp_type",
            field=models.IntegerField(
                choices=[
                    (1, "Exercise"),
                    (2, "Task"),
                    (3, "Lecture"),
                    (4, "Matriculation Basic"),
                    (5, "Matriculation Extended"),
                    (6, "Eight Exam"),
                ]
            ),
        ),
    ]
