# Generated by Django 5.2.10 on 2026-02-07 22:34

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examination_tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("warmups", models.PositiveIntegerField(default=0)),
                ("exam_tasks", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tasks_per_day",
                    models.PositiveIntegerField(
                        default=5, help_text="Number of math tasks per day"
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("exam_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_warmup", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                (
                    "daily",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="training_calendar.dailystudy",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_tasks.examtask",
                    ),
                ),
            ],
        ),
    ]
