# Generated by Django 5.2.3 on 2025-08-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0006_book_section_and_more"),
        ("training_calendar", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_tasks.examtask",
            ),
        ),
    ]
