# Generated by Django 5.2.6 on 2025-10-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_tasks", "0003_exam_subject_alter_examtask_task_screen"),
        ("quizes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="type",
        ),
        migrations.AddField(
            model_name="quiz",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_topics",
                to="examination_tasks.section",
                verbose_name="Section",
            ),
            preserve_default=False,
        ),
    ]
