# Generated by Django 5.2.3 on 2025-06-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="explanation_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="explanation_picture/"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizes.quiz",
                    ),
                ),
            ],
        ),
    ]
