# Generated by Django 5.2.10 on 2026-02-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quizes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quizes.quizattempt",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizes.question"
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_answers",
            field=models.ManyToManyField(
                related_name="user_quiz_answers", to="quizes.answer"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("attempt", "question")},
        ),
    ]
