name: TutorApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Update PIP
      run: |
        python -m pip install --upgrade pip
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Lint with bandit
      run: |
        bandit -r TuturApp
    - name: Run Safety
      run: |
        safety check
      continue-on-error: true
    - name: Run DjLint
      run: |
        djlint . --lint
    - name: Run Pytest
      run: |
        python manage.py test
      env:
        DB_USER: ${{ env.DB_USER }}
        DB_NAME: ${{ env.DB_NAME }}
        DB_PORT: ${{ env.DB_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#    - name: Upload coverage report
#      uses: codecov/codecov-action@v4
#      env:
#        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}